export const AppActionConst = {
  ACTION_REGISTER_USER_LOADING: 'ACTION_REGISTER_USER_LOADING',
  ACTION_REGISTER_USER: 'ACTION_REGISTER_USER',
  ACTION_REGISTER_USER_SUCCESS: 'ACTION_REGISTER_USER_SUCCESS',
  ACTION_REGISTER_USER_ERROR: 'ACTION_REGISTER_USER_ERROR',
  ACTION_GET_USER_MEETUP_LIST_STARTED: 'ACTION_GET_USER_MEETUP_LIST_STARTED',
  ACTION_GET_USER_MEETUP_LIST_LOADING: 'ACTION_GET_USER_MEETUP_LIST_LOADING',
  ACTION_GET_USER_MEETUP_LIST_SUCCESS: 'ACTION_GET_USER_MEETUP_LIST_SUCCESS',
  ACTION_GET_USER_MEETUP_LIST_ERROR: 'ACTION_GET_USER_MEETUP_LIST_ERROR',
};
